export const ACADEMIC_ERROR_CODES = {
  CLASS_HAS_STUDENTS: "CLASS_HAS_STUDENTS",
  DUPLICATE_CLASS: "DUPLICATE_CLASS",
  INVALID_LEVEL: "INVALID_LEVEL",
  DUPLICATE_SUBJECT: "DUPLICATE_SUBJECT",
  SUBJECT_HAS_LINKS: "SUBJECT_HAS_LINKS",
  INVALID_CLASS: "INVALID_CLASS",
} as const;

export type AcademicErrorCode = (typeof ACADEMIC_ERROR_CODES)[keyof typeof ACADEMIC_ERROR_CODES];
