-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.analytics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_type text NOT NULL,
  user_id uuid,
  event_data jsonb,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT analytics_pkey PRIMARY KEY (id),
  CONSTRAINT analytics_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.at_risk_flags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  learner_id uuid NOT NULL,
  flag_type text DEFAULT 'LOW_PROGRESS'::text CHECK (flag_type = ANY (ARRAY['LOW_PROGRESS'::text, 'MULTIPLE_FAILURES'::text, 'NO_RECENT_ACTIVITY'::text, 'BEHAVIORAL'::text])),
  severity text DEFAULT 'MEDIUM'::text CHECK (severity = ANY (ARRAY['LOW'::text, 'MEDIUM'::text, 'HIGH'::text, 'CRITICAL'::text])),
  reason text,
  description text,
  detected_by uuid,
  teacher_notes text,
  is_resolved boolean DEFAULT false,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT at_risk_flags_pkey PRIMARY KEY (id),
  CONSTRAINT at_risk_flags_detected_by_fkey FOREIGN KEY (detected_by) REFERENCES public.users(id),
  CONSTRAINT at_risk_flags_learner_id_fkey FOREIGN KEY (learner_id) REFERENCES public.users(id)
);
CREATE TABLE public.audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  actor_id uuid,
  action text NOT NULL,
  action_type text,
  table_name text,
  resource_type text,
  resource_id uuid,
  record_id uuid,
  description text,
  changes jsonb,
  old_values jsonb,
  new_values jsonb,
  ip_address text,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT audit_log_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.users(id)
);
CREATE TABLE public.badges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text,
  badge_icon bytea,
  badge_icon_url text,
  icon_url text,
  criteria jsonb,
  unlock_condition text,
  xp_reward integer DEFAULT 10,
  rarity text DEFAULT 'COMMON'::text CHECK (rarity = ANY (ARRAY['COMMON'::text, 'UNCOMMON'::text, 'RARE'::text, 'EPIC'::text, 'LEGENDARY'::text])),
  is_hidden boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT badges_pkey PRIMARY KEY (id)
);
CREATE TABLE public.certificates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  learner_id uuid NOT NULL,
  issued_by uuid NOT NULL,
  lesson_id uuid,
  module_id uuid,
  certificate_type text DEFAULT 'LESSON'::text CHECK (certificate_type = ANY (ARRAY['LESSON'::text, 'MODULE'::text, 'COURSE'::text])),
  achievement_type text,
  certificate_name text,
  certificate_number text UNIQUE,
  certificate_url text,
  pdf_url text,
  qr_code_url text,
  issue_date timestamp with time zone DEFAULT now(),
  earned_date timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  verification_uuid uuid DEFAULT gen_random_uuid() UNIQUE,
  is_verified boolean DEFAULT false,
  is_revoked boolean DEFAULT false,
  revoked_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT certificates_pkey PRIMARY KEY (id),
  CONSTRAINT certificates_issued_by_fkey FOREIGN KEY (issued_by) REFERENCES public.users(id),
  CONSTRAINT certificates_learner_id_fkey FOREIGN KEY (learner_id) REFERENCES public.users(id),
  CONSTRAINT certificates_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id),
  CONSTRAINT certificates_module_id_fkey FOREIGN KEY (module_id) REFERENCES public.lesson_modules(id)
);
CREATE TABLE public.class_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  class_id uuid NOT NULL,
  learner_id uuid NOT NULL,
  enrollment_status text DEFAULT 'ACTIVE'::text CHECK (enrollment_status = ANY (ARRAY['ACTIVE'::text, 'SUSPENDED'::text, 'COMPLETED'::text, 'WITHDRAWN'::text])),
  joined_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  enrolled_date timestamp with time zone DEFAULT now(),
  progress_percent integer DEFAULT 0,
  total_xp integer DEFAULT 0,
  CONSTRAINT class_members_pkey PRIMARY KEY (id),
  CONSTRAINT class_members_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT class_members_learner_id_fkey FOREIGN KEY (learner_id) REFERENCES public.users(id)
);
CREATE TABLE public.class_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  class_id uuid NOT NULL UNIQUE,
  minimum_passing_score numeric DEFAULT 70.00,
  grading_weights jsonb DEFAULT '{"projects": 35, "exercises": 40, "participation": 25}'::jsonb,
  auto_unlock_threshold numeric DEFAULT 70.00,
  max_attempts_per_exercise integer DEFAULT 5 CHECK (max_attempts_per_exercise >= 1 AND max_attempts_per_exercise <= 20),
  allow_retakes boolean DEFAULT true,
  credential_expiry_days integer DEFAULT 90 CHECK (credential_expiry_days >= 1 AND credential_expiry_days <= 365),
  max_enrollment_limit integer DEFAULT 30 CHECK (max_enrollment_limit >= 5 AND max_enrollment_limit <= 100),
  enable_peer_review boolean DEFAULT false,
  created_by uuid NOT NULL,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_by uuid,
  CONSTRAINT class_settings_pkey PRIMARY KEY (id),
  CONSTRAINT class_settings_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT class_settings_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT class_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.class_tiers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tier_name text NOT NULL UNIQUE,
  tier_level integer NOT NULL UNIQUE,
  curriculum_phase_id uuid NOT NULL,
  description text,
  min_completed_phase_percent integer DEFAULT 0,
  max_students integer,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT class_tiers_pkey PRIMARY KEY (id),
  CONSTRAINT class_tiers_curriculum_phase_id_fkey FOREIGN KEY (curriculum_phase_id) REFERENCES public.curriculum_phases(id)
);
CREATE TABLE public.classes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  teacher_id uuid NOT NULL,
  name text NOT NULL,
  class_name text,
  code text NOT NULL UNIQUE,
  class_code text,
  description text,
  grade_level integer,
  max_learners integer,
  enrollment_limit integer,
  academic_year text,
  is_active boolean DEFAULT true,
  order_index integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  learning_mode text,
  created_by uuid,
  class_tier_id uuid,
  is_auto_assigned boolean DEFAULT true,
  assignment_reason text,
  CONSTRAINT classes_pkey PRIMARY KEY (id),
  CONSTRAINT classes_class_tier_id_fkey FOREIGN KEY (class_tier_id) REFERENCES public.class_tiers(id),
  CONSTRAINT classes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT classes_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.users(id)
);
CREATE TABLE public.code_execution_results (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  input_code text NOT NULL,
  stdout text,
  stderr text,
  execution_time_ms integer,
  memory_used_kb integer,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'success'::text, 'error'::text, 'timeout'::text, 'out_of_memory'::text])),
  error_type text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT code_execution_results_pkey PRIMARY KEY (id),
  CONSTRAINT code_execution_results_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.code_submissions(id)
);
CREATE TABLE public.code_submissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  learner_id uuid NOT NULL,
  lesson_id uuid NOT NULL,
  exercise_id uuid,
  block_code text,
  python_code text NOT NULL,
  submission_type text DEFAULT 'EXERCISE'::text CHECK (submission_type = ANY (ARRAY['EXERCISE'::text, 'PROJECT'::text, 'PRACTICE'::text])),
  submitted_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT code_submissions_pkey PRIMARY KEY (id),
  CONSTRAINT code_submissions_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id),
  CONSTRAINT code_submissions_learner_id_fkey FOREIGN KEY (learner_id) REFERENCES public.users(id),
  CONSTRAINT code_submissions_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id)
);
CREATE TABLE public.credentials_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  student_number character varying NOT NULL,
  class_code character varying NOT NULL,
  class_level character varying,
  temp_password character varying NOT NULL,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  reset_by uuid,
  reset_reason character varying,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT credentials_log_pkey PRIMARY KEY (id),
  CONSTRAINT fk_credentials_log_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_credentials_log_reset_by FOREIGN KEY (reset_by) REFERENCES public.users(id),
  CONSTRAINT fk_credentials_log_user_id FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.curriculum_phases (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  phase_number integer NOT NULL UNIQUE,
  phase_name text NOT NULL,
  description text,
  min_age integer,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT curriculum_phases_pkey PRIMARY KEY (id)
);
CREATE TABLE public.custom_badges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  class_id uuid NOT NULL,
  teacher_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  icon_url text,
  color_code character varying,
  criteria_type character varying NOT NULL CHECK (criteria_type::text = ANY (ARRAY['MILESTONE'::character varying::text, 'EXERCISE_COMPLETION'::character varying::text, 'STREAK'::character varying::text, 'CUSTOM'::character varying::text])),
  criteria_details jsonb,
  xp_reward integer DEFAULT 50,
  badge_status character varying DEFAULT 'ACTIVE'::character varying CHECK (badge_status::text = ANY (ARRAY['ACTIVE'::character varying::text, 'DRAFT'::character varying::text, 'ARCHIVED'::character varying::text])),
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT custom_badges_pkey PRIMARY KEY (id),
  CONSTRAINT custom_badges_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT custom_badges_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.users(id)
);
CREATE TABLE public.email_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  recipient_email text NOT NULL,
  recipient_id uuid,
  email_type text NOT NULL CHECK (email_type = ANY (ARRAY['REGISTRATION'::text, 'APPROVAL'::text, 'REJECTION'::text, 'PASSWORD_RESET'::text, 'PROGRESS_UPDATE'::text, 'AT_RISK_ALERT'::text, 'BADGE_EARNED'::text, 'CERTIFICATE_EARNED'::text, 'MESSAGE_NOTIFICATION'::text, 'LESSON_ASSIGNMENT'::text, 'ASSIGNMENT_DUE'::text, 'OTHER'::text])),
  learner_name text,
  subject text,
  body text,
  message_id text,
  is_sent boolean DEFAULT false,
  sent_at timestamp with time zone,
  status text,
  failed_reason text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_logs_pkey PRIMARY KEY (id),
  CONSTRAINT email_logs_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.users(id)
);
CREATE TABLE public.exercise_test_results (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  test_case_index integer NOT NULL,
  test_name text,
  input_data text,
  expected_output text,
  actual_output text,
  passed boolean DEFAULT false,
  error_message text,
  execution_time_ms integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT exercise_test_results_pkey PRIMARY KEY (id),
  CONSTRAINT exercise_test_results_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(id)
);
CREATE TABLE public.exercises (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lesson_id uuid NOT NULL,
  teacher_id uuid NOT NULL,
  exercise_number integer,
  title text NOT NULL,
  description text,
  exercise_type text DEFAULT 'CODE'::text CHECK (exercise_type = ANY (ARRAY['CODE'::text, 'MULTIPLE_CHOICE'::text, 'FILL_BLANK'::text, 'DRAG_DROP'::text])),
  blockly_xml text,
  python_template_code text,
  starter_code text,
  instructions text,
  test_code text,
  expected_output text,
  sample_input text,
  test_cases jsonb,
  difficulty text DEFAULT 'BEGINNER'::text CHECK (difficulty = ANY (ARRAY['BEGINNER'::text, 'INTERMEDIATE'::text, 'ADVANCED'::text])),
  difficulty_level integer,
  max_score integer DEFAULT 100,
  xp_reward integer DEFAULT 5,
  is_blockly_auto_graded boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  solution_code text,
  hints ARRAY DEFAULT ARRAY[]::text[],
  points integer DEFAULT 10,
  is_auto_graded boolean DEFAULT true,
  auto_grading_enabled boolean DEFAULT true,
  question_data jsonb,
  CONSTRAINT exercises_pkey PRIMARY KEY (id),
  CONSTRAINT exercises_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id),
  CONSTRAINT exercises_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.users(id)
);
CREATE TABLE public.grades (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT grades_pkey PRIMARY KEY (id)
);
CREATE TABLE public.guardians (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  learner_id uuid NOT NULL,
  email text NOT NULL,
  phone_number text,
  guardian_email text,
  guardian_name text,
  relationship text DEFAULT 'PARENT'::text CHECK (relationship = ANY (ARRAY['PARENT'::text, 'GUARDIAN'::text, 'CAREGIVER'::text, 'OTHER'::text])),
  is_verified boolean DEFAULT false,
  verification_token text,
  verified_at timestamp with time zone,
  notification_preferences jsonb DEFAULT '{"certificates": true, "at_risk_alerts": true, "weekly_progress": true, "milestone_badges": true, "approval_notifications": true, "registration_confirmation": true}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT guardians_pkey PRIMARY KEY (id),
  CONSTRAINT guardians_learner_id_fkey FOREIGN KEY (learner_id) REFERENCES public.users(id)
);
CREATE TABLE public.learner_analytics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  learner_id uuid NOT NULL,
  class_id uuid,
  total_exercises_attempted integer DEFAULT 0,
  total_exercises_passed integer DEFAULT 0,
  total_exercises_failed integer DEFAULT 0,
  average_score numeric DEFAULT 0,
  total_time_spent_hours numeric DEFAULT 0,
  exercises_completed_percent numeric DEFAULT 0,
  modules_completed integer DEFAULT 0,
  lessons_completed integer DEFAULT 0,
  current_streak_days integer DEFAULT 0,
  longest_streak_days integer DEFAULT 0,
  last_active_at timestamp with time zone,
  is_at_risk boolean DEFAULT false,
  at_risk_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  current_class_id uuid,
  current_phase_id uuid,
  phase_completion_percent integer DEFAULT 0,
  CONSTRAINT learner_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT learner_analytics_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT learner_analytics_current_class_id_fkey FOREIGN KEY (current_class_id) REFERENCES public.classes(id),
  CONSTRAINT learner_analytics_current_phase_id_fkey FOREIGN KEY (current_phase_id) REFERENCES public.curriculum_phases(id),
  CONSTRAINT learner_analytics_learner_id_fkey FOREIGN KEY (learner_id) REFERENCES public.users(id)
);
CREATE TABLE public.learner_badges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  learner_id uuid NOT NULL,
  badge_id uuid NOT NULL,
  earned_at timestamp with time zone DEFAULT now(),
  notification_sent boolean DEFAULT false,
  CONSTRAINT learner_badges_pkey PRIMARY KEY (id),
  CONSTRAINT learner_badges_badge_id_fkey FOREIGN KEY (badge_id) REFERENCES public.badges(id),
  CONSTRAINT learner_badges_learner_id_fkey FOREIGN KEY (learner_id) REFERENCES public.users(id)
);
CREATE TABLE public.learner_block_unlocks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  learner_id uuid NOT NULL,
  block_type text NOT NULL,
  block_category text,
  unlocked_by uuid,
  unlock_reason text,
  unlocked_at timestamp with time zone DEFAULT now(),
  CONSTRAINT learner_block_unlocks_pkey PRIMARY KEY (id),
  CONSTRAINT learner_block_unlocks_learner_id_fkey FOREIGN KEY (learner_id) REFERENCES public.users(id),
  CONSTRAINT learner_block_unlocks_unlocked_by_fkey FOREIGN KEY (unlocked_by) REFERENCES public.users(id)
);
CREATE TABLE public.learner_class_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  learner_id uuid NOT NULL,
  class_id uuid NOT NULL,
  class_tier_id uuid NOT NULL,
  assignment_reason text,
  assigned_at timestamp with time zone DEFAULT now(),
  promoted_at timestamp with time zone,
  previous_class_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT learner_class_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT learner_class_assignments_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT learner_class_assignments_class_tier_id_fkey FOREIGN KEY (class_tier_id) REFERENCES public.class_tiers(id),
  CONSTRAINT learner_class_assignments_learner_id_fkey FOREIGN KEY (learner_id) REFERENCES public.users(id)
);
CREATE TABLE public.learner_custom_badges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  learner_id uuid NOT NULL,
  custom_badge_id uuid NOT NULL,
  earned_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  earned_by uuid,
  CONSTRAINT learner_custom_badges_pkey PRIMARY KEY (id),
  CONSTRAINT learner_custom_badges_custom_badge_id_fkey FOREIGN KEY (custom_badge_id) REFERENCES public.custom_badges(id),
  CONSTRAINT learner_custom_badges_earned_by_fkey FOREIGN KEY (earned_by) REFERENCES public.users(id),
  CONSTRAINT learner_custom_badges_learner_id_fkey FOREIGN KEY (learner_id) REFERENCES public.users(id)
);
CREATE TABLE public.learner_module_progress (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  learner_id uuid NOT NULL,
  module_id uuid NOT NULL,
  class_id uuid,
  progress_percent integer DEFAULT 0,
  lessons_completed integer DEFAULT 0,
  total_lessons integer DEFAULT 0,
  module_xp_earned integer DEFAULT 0,
  is_completed boolean DEFAULT false,
  completion_date timestamp with time zone,
  last_accessed timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT learner_module_progress_pkey PRIMARY KEY (id),
  CONSTRAINT learner_module_progress_learner_id_fkey FOREIGN KEY (learner_id) REFERENCES public.users(id),
  CONSTRAINT learner_module_progress_module_id_fkey FOREIGN KEY (module_id) REFERENCES public.lesson_modules(id)
);
CREATE TABLE public.learner_progress (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  learner_id uuid NOT NULL,
  module_id uuid,
  lesson_id uuid,
  exercise_id uuid,
  progress_percent integer DEFAULT 0,
  completion_status text DEFAULT 'NOT_STARTED'::text CHECK (completion_status = ANY (ARRAY['NOT_STARTED'::text, 'IN_PROGRESS'::text, 'COMPLETED'::text, 'MASTERED'::text])),
  best_score integer,
  average_score numeric,
  total_attempts integer DEFAULT 0,
  total_time_spent_seconds integer DEFAULT 0,
  last_attempted_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT learner_progress_pkey PRIMARY KEY (id),
  CONSTRAINT learner_progress_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id),
  CONSTRAINT learner_progress_learner_id_fkey FOREIGN KEY (learner_id) REFERENCES public.users(id),
  CONSTRAINT learner_progress_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id),
  CONSTRAINT learner_progress_module_id_fkey FOREIGN KEY (module_id) REFERENCES public.lesson_modules(id)
);
CREATE TABLE public.learner_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  learner_id uuid NOT NULL,
  class_id uuid,
  session_start_time timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  session_end_time timestamp without time zone,
  duration_seconds integer,
  ip_address inet,
  user_agent text,
  device_type character varying,
  exercises_attempted integer DEFAULT 0,
  lessons_viewed integer DEFAULT 0,
  time_spent_on_exercises integer DEFAULT 0,
  time_spent_on_lessons integer DEFAULT 0,
  is_active boolean DEFAULT true,
  session_type character varying DEFAULT 'NORMAL'::character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT learner_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT learner_sessions_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT learner_sessions_learner_id_fkey FOREIGN KEY (learner_id) REFERENCES public.users(id)
);
CREATE TABLE public.learner_unlocks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  learner_id uuid NOT NULL,
  module_id uuid,
  lesson_id uuid NOT NULL,
  unlocked_by_lesson_id uuid,
  unlock_reason text DEFAULT 'lesson_mastery'::text,
  unlocked_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT learner_unlocks_pkey PRIMARY KEY (id),
  CONSTRAINT learner_unlocks_learner_id_fkey FOREIGN KEY (learner_id) REFERENCES public.users(id),
  CONSTRAINT learner_unlocks_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id),
  CONSTRAINT learner_unlocks_module_id_fkey FOREIGN KEY (module_id) REFERENCES public.lesson_modules(id),
  CONSTRAINT learner_unlocks_unlocked_by_lesson_id_fkey FOREIGN KEY (unlocked_by_lesson_id) REFERENCES public.lessons(id)
);
CREATE TABLE public.learner_weak_areas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  learner_id uuid NOT NULL,
  teacher_id uuid,
  topic_name text NOT NULL,
  description text,
  identified_reason text,
  confidence_score numeric DEFAULT 0.50,
  last_failed_attempt_at timestamp with time zone,
  recommendation text,
  is_resolved boolean DEFAULT false,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT learner_weak_areas_pkey PRIMARY KEY (id),
  CONSTRAINT learner_weak_areas_learner_id_fkey FOREIGN KEY (learner_id) REFERENCES public.users(id),
  CONSTRAINT learner_weak_areas_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.users(id)
);
CREATE TABLE public.learning_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  learner_id uuid NOT NULL,
  class_id uuid,
  lesson_id uuid,
  session_start timestamp with time zone DEFAULT now(),
  session_end timestamp with time zone,
  time_spent_minutes integer,
  exercises_attempted integer DEFAULT 0,
  exercises_passed integer DEFAULT 0,
  exercises_failed integer DEFAULT 0,
  total_score integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT learning_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT learning_sessions_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT learning_sessions_learner_id_fkey FOREIGN KEY (learner_id) REFERENCES public.users(id),
  CONSTRAINT learning_sessions_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id)
);
CREATE TABLE public.lesson_modules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  teacher_id uuid NOT NULL,
  class_id uuid,
  name text NOT NULL,
  description text,
  order_index integer,
  is_published boolean DEFAULT false,
  is_locked boolean DEFAULT false,
  difficulty_level integer DEFAULT 1,
  xp_reward integer DEFAULT 10,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  module_order integer,
  stage_key text,
  stage_label text,
  unlock_min_score integer DEFAULT 70,
  blockly_required boolean DEFAULT true,
  estimated_hours integer DEFAULT 24,
  icon_name text,
  learning_objectives ARRAY DEFAULT ARRAY[]::text[],
  curriculum_phase_id uuid,
  phase_sequence integer,
  CONSTRAINT lesson_modules_pkey PRIMARY KEY (id),
  CONSTRAINT lesson_modules_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT lesson_modules_curriculum_phase_id_fkey FOREIGN KEY (curriculum_phase_id) REFERENCES public.curriculum_phases(id),
  CONSTRAINT lesson_modules_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.users(id)
);
CREATE TABLE public.lessons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  teacher_id uuid NOT NULL,
  class_id uuid NOT NULL,
  module_id uuid,
  title text NOT NULL,
  description text,
  content jsonb,
  learning_mode text DEFAULT 'BLOCKLY'::text CHECK (learning_mode = ANY (ARRAY['BLOCKLY'::text, 'PYTHON'::text, 'BOTH'::text])),
  blockly_xml text,
  python_template_code text,
  age_group text DEFAULT 'ALL'::text CHECK (age_group = ANY (ARRAY['6-8'::text, '7-9'::text, '9-12'::text, '13-15'::text, '16-18'::text, 'ALL'::text])),
  difficulty_level integer DEFAULT 1,
  expected_output text,
  order_index integer,
  is_active boolean DEFAULT true,
  is_locked boolean DEFAULT false,
  is_published boolean DEFAULT false,
  xp_reward integer DEFAULT 10,
  time_limit_minutes integer,
  published_at timestamp with time zone,
  publish_scheduled_for timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  lesson_order integer,
  unlock_min_score integer DEFAULT 70,
  blockly_required boolean DEFAULT true,
  content_type text DEFAULT 'lesson'::text,
  blockly_enabled boolean DEFAULT true,
  show_code_panel boolean DEFAULT true,
  theory_content text,
  challenge_description text,
  estimated_minutes integer DEFAULT 30,
  CONSTRAINT lessons_pkey PRIMARY KEY (id),
  CONSTRAINT lessons_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT lessons_module_id_fkey FOREIGN KEY (module_id) REFERENCES public.lesson_modules(id),
  CONSTRAINT lessons_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.users(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sender_id uuid NOT NULL,
  recipient_id uuid NOT NULL,
  message_type text DEFAULT 'TEXT'::text CHECK (message_type = ANY (ARRAY['TEXT'::text, 'CODE_SHARE'::text, 'FEEDBACK'::text, 'ANNOUNCEMENT'::text])),
  subject text,
  content text NOT NULL,
  attachment_url text,
  is_read boolean DEFAULT false,
  read_at timestamp with time zone,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  body text NOT NULL DEFAULT ''::text,
  reply_to_id uuid,
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.users(id),
  CONSTRAINT messages_reply_to_id_fkey FOREIGN KEY (reply_to_id) REFERENCES public.messages(id),
  CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.users(id)
);
CREATE TABLE public.module_lessons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  module_id uuid NOT NULL,
  lesson_id uuid NOT NULL,
  order_index integer DEFAULT 0,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT module_lessons_pkey PRIMARY KEY (id),
  CONSTRAINT module_lessons_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id),
  CONSTRAINT module_lessons_module_id_fkey FOREIGN KEY (module_id) REFERENCES public.lesson_modules(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text,
  phone text,
  full_name text NOT NULL,
  password_hash text,
  avatar_url text,
  avatar_storage_path text,
  avatar_uploaded_at timestamp with time zone,
  avatar_file_size integer,
  avatar_mime_type text,
  role text NOT NULL DEFAULT 'LEARNER'::text CHECK (role = ANY (ARRAY['ADMIN'::text, 'TEACHER'::text, 'LEARNER'::text, 'STUDENT'::text])),
  display_name text,
  account_status text NOT NULL DEFAULT 'PENDING'::text CHECK (account_status = ANY (ARRAY['PENDING'::text, 'ACTIVE'::text, 'SUSPENDED'::text, 'INACTIVE'::text, 'DELETED'::text])),
  learner_age_group text CHECK (learner_age_group = ANY (ARRAY['7-9'::text, '10-12'::text, '13-15'::text, '16-18'::text, 'ADULT'::text])),
  learner_grade integer,
  learning_mode text CHECK (learning_mode = ANY (ARRAY['BLOCKLY'::text, 'PYTHON'::text, NULL::text])),
  class_id uuid,
  guardian_id uuid,
  school_id uuid,
  requires_profile_update boolean DEFAULT false,
  xp integer DEFAULT 0,
  streak integer DEFAULT 0,
  is_approved boolean DEFAULT false,
  two_factor_enabled boolean DEFAULT false,
  two_factor_secret text,
  email_verified boolean DEFAULT false,
  phone_verified boolean DEFAULT false,
  registered_at timestamp with time zone DEFAULT now(),
  last_login timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  approval_date timestamp with time zone,
  declined_reason text,
  deleted_at timestamp with time zone,
  date_of_birth date,
  guardian_email text,
  bio text,
  school character varying,
  student_number character varying UNIQUE,
  credentials_generated_at timestamp without time zone,
  last_password_reset_at timestamp without time zone,
  last_password_reset_by uuid,
  class_code character varying,
  class_level character varying,
  temp_password character varying,
  learner_pin text,
  pin_created_at timestamp with time zone,
  temporary_password_hash text,
  first_login_completed boolean DEFAULT false,
  password_changed_at timestamp with time zone,
  last_login_at timestamp with time zone,
  status text DEFAULT 'ACTIVE'::text,
  temporary_password character varying,
  name text,
  school_class_id uuid,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_last_password_reset_by_fkey FOREIGN KEY (last_password_reset_by) REFERENCES public.users(id),
  CONSTRAINT users_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT users_school_class_id_fkey FOREIGN KEY (school_class_id) REFERENCES public.school_classes(id)
);
CREATE TABLE public.notification_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  teacher_id uuid NOT NULL,
  notification_rule_id uuid,
  recipient_email text,
  event_type text NOT NULL,
  subject text,
  message text,
  delivery_status character varying DEFAULT 'SENT'::character varying CHECK (delivery_status::text = ANY (ARRAY['SENT'::character varying::text, 'FAILED'::character varying::text, 'BOUNCED'::character varying::text, 'DELIVERED'::character varying::text])),
  delivery_channel character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  sent_at timestamp without time zone,
  delivery_at timestamp without time zone,
  CONSTRAINT notification_log_pkey PRIMARY KEY (id),
  CONSTRAINT notification_log_notification_rule_id_fkey FOREIGN KEY (notification_rule_id) REFERENCES public.notification_rules(id),
  CONSTRAINT notification_log_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.users(id)
);
CREATE TABLE public.notification_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  teacher_id uuid NOT NULL,
  class_id uuid,
  event_type character varying NOT NULL CHECK (event_type::text = ANY (ARRAY['EXERCISE_SUBMITTED'::character varying::text, 'BADGE_EARNED'::character varying::text, 'PROGRESS_MILESTONE'::character varying::text, 'LEARNER_AT_RISK'::character varying::text, 'LEARNER_REGISTERED'::character varying::text, 'LEARNER_APPROVED'::character varying::text, 'LOW_ATTENDANCE'::character varying::text, 'ASSIGNMENT_DUE'::character varying::text, 'PEER_REVIEW_READY'::character varying::text])),
  notify_via_email boolean DEFAULT true,
  notify_via_dashboard boolean DEFAULT true,
  notify_via_sms boolean DEFAULT false,
  notification_frequency character varying DEFAULT 'IMMEDIATE'::character varying CHECK (notification_frequency::text = ANY (ARRAY['IMMEDIATE'::character varying::text, 'DAILY_DIGEST'::character varying::text, 'WEEKLY_DIGEST'::character varying::text, 'DISABLED'::character varying::text])),
  min_severity character varying,
  specific_learner_id uuid,
  is_enabled boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT notification_rules_pkey PRIMARY KEY (id),
  CONSTRAINT notification_rules_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT notification_rules_specific_learner_id_fkey FOREIGN KEY (specific_learner_id) REFERENCES public.users(id),
  CONSTRAINT notification_rules_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.users(id)
);
CREATE TABLE public.platform_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  setting_key text NOT NULL UNIQUE,
  setting_value text,
  description text,
  is_global boolean DEFAULT true,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT platform_settings_pkey PRIMARY KEY (id),
  CONSTRAINT platform_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.profile_image_uploads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  original_filename text NOT NULL,
  storage_path text NOT NULL,
  file_size integer NOT NULL,
  mime_type text NOT NULL,
  public_url text NOT NULL,
  ip_address text,
  user_agent text,
  upload_status text DEFAULT 'SUCCESS'::text CHECK (upload_status = ANY (ARRAY['SUCCESS'::text, 'FAILED'::text, 'DELETED'::text])),
  error_message text,
  uploaded_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT profile_image_uploads_pkey PRIMARY KEY (id),
  CONSTRAINT profile_image_uploads_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.progress (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lesson_id uuid NOT NULL,
  learner_id uuid NOT NULL,
  class_id uuid,
  current_card_index integer DEFAULT 0,
  is_completed boolean DEFAULT false,
  completed_at timestamp with time zone,
  started_at timestamp with time zone DEFAULT now(),
  lessons_completed integer DEFAULT 0,
  total_lessons integer DEFAULT 0,
  overall_progress_percent integer DEFAULT 0,
  total_xp integer DEFAULT 0,
  rank integer,
  section_id uuid,
  last_activity timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT progress_pkey PRIMARY KEY (id),
  CONSTRAINT progress_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT progress_learner_id_fkey FOREIGN KEY (learner_id) REFERENCES public.users(id),
  CONSTRAINT progress_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id)
);
CREATE TABLE public.resource_notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  learner_id uuid NOT NULL,
  resource_id uuid NOT NULL,
  is_read boolean DEFAULT false,
  read_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT resource_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT resource_notifications_learner_id_fkey FOREIGN KEY (learner_id) REFERENCES public.users(id),
  CONSTRAINT resource_notifications_resource_id_fkey FOREIGN KEY (resource_id) REFERENCES public.resources(id)
);
CREATE TABLE public.resources (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  teacher_id uuid NOT NULL,
  class_id uuid,
  title text NOT NULL,
  description text,
  file_url text,
  resource_type text NOT NULL DEFAULT 'file'::text CHECK (resource_type = ANY (ARRAY['file'::text, 'link'::text, 'text'::text])),
  file_type text,
  file_size integer,
  link_url text,
  is_archived boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT resources_pkey PRIMARY KEY (id),
  CONSTRAINT resources_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT resources_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.users(id)
);
CREATE TABLE public.roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  role_name text NOT NULL UNIQUE,
  description text,
  permissions jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.schools (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  address text,
  district text,
  country text DEFAULT 'Uganda'::text,
  contact_email text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  slug text NOT NULL UNIQUE,
  logo_url text,
  stamp_url text,
  email text,
  phone text,
  school_type text CHECK (school_type IS NULL OR (school_type = ANY (ARRAY['primary'::text, 'secondary'::text, 'both'::text]))),
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['setup'::text, 'active'::text, 'suspended'::text])),
  subscription_status text DEFAULT 'unpaid'::text CHECK (subscription_status = ANY (ARRAY['unpaid'::text, 'active'::text, 'expired'::text])),
  subscription_term text,
  subscription_year integer,
  schoolpay_code text,
  CONSTRAINT schools_pkey PRIMARY KEY (id)
);
CREATE TABLE public.submissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  exercise_id uuid NOT NULL,
  learner_id uuid NOT NULL,
  lesson_id uuid NOT NULL,
  code_text text NOT NULL,
  blockly_xml text,
  python_code text,
  generated_from_blockly boolean DEFAULT false,
  status text DEFAULT 'SUBMITTED'::text CHECK (status = ANY (ARRAY['SUBMITTED'::text, 'GRADED'::text, 'NEEDS_REVISION'::text, 'ACCEPTED'::text, 'APPROVED'::text, 'REJECTED'::text])),
  score integer,
  feedback text,
  is_auto_graded boolean DEFAULT false,
  is_manually_graded boolean DEFAULT false,
  graded_by uuid,
  graded_at timestamp with time zone,
  attempt_number integer DEFAULT 1,
  time_spent_seconds integer,
  execution_time_ms integer,
  compiler_output text,
  tests_passed integer DEFAULT 0,
  tests_total integer DEFAULT 0,
  console_output text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT submissions_pkey PRIMARY KEY (id),
  CONSTRAINT submissions_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id),
  CONSTRAINT submissions_graded_by_fkey FOREIGN KEY (graded_by) REFERENCES public.users(id),
  CONSTRAINT submissions_learner_id_fkey FOREIGN KEY (learner_id) REFERENCES public.users(id),
  CONSTRAINT submissions_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id)
);
CREATE TABLE public.turtle_graphics_results (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  svg_output text NOT NULL,
  canvas_width integer DEFAULT 800,
  canvas_height integer DEFAULT 600,
  execution_time_ms integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT turtle_graphics_results_pkey PRIMARY KEY (id),
  CONSTRAINT turtle_graphics_results_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.code_submissions(id)
);
CREATE TABLE public.schema_migrations (
  filename text NOT NULL,
  applied_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT schema_migrations_pkey PRIMARY KEY (filename)
);
CREATE TABLE public.super_admins (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  name text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT super_admins_pkey PRIMARY KEY (id)
);
CREATE TABLE public.school_classes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid NOT NULL,
  level text NOT NULL,
  stream text,
  capacity integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT school_classes_pkey PRIMARY KEY (id),
  CONSTRAINT school_classes_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id)
);
CREATE TABLE public.school_subjects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid NOT NULL,
  name text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT school_subjects_pkey PRIMARY KEY (id),
  CONSTRAINT school_subjects_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id)
);
CREATE TABLE public.school_class_subjects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid NOT NULL,
  class_id uuid NOT NULL,
  subject_id uuid NOT NULL,
  CONSTRAINT school_class_subjects_pkey PRIMARY KEY (id),
  CONSTRAINT school_class_subjects_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT school_class_subjects_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.school_classes(id),
  CONSTRAINT school_class_subjects_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.school_subjects(id)
);
CREATE TABLE public.academic_years (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid NOT NULL,
  year integer NOT NULL,
  is_current boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT academic_years_pkey PRIMARY KEY (id),
  CONSTRAINT academic_years_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id)
);
CREATE TABLE public.terms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid NOT NULL,
  academic_year_id uuid NOT NULL,
  name text NOT NULL,
  start_date date,
  end_date date,
  is_current boolean DEFAULT false,
  CONSTRAINT terms_pkey PRIMARY KEY (id),
  CONSTRAINT terms_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT terms_academic_year_id_fkey FOREIGN KEY (academic_year_id) REFERENCES public.academic_years(id)
);
CREATE TABLE public.grading_scales (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid NOT NULL,
  label text NOT NULL,
  min_score integer NOT NULL,
  max_score integer NOT NULL,
  description text,
  CONSTRAINT grading_scales_pkey PRIMARY KEY (id),
  CONSTRAINT grading_scales_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id)
);
CREATE TABLE public.subscription_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid NOT NULL,
  amount integer NOT NULL,
  term text NOT NULL,
  year integer NOT NULL,
  schoolpay_ref text,
  paid_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT subscription_payments_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_payments_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id)
);
CREATE TABLE public.webhook_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source text NOT NULL,
  payload jsonb NOT NULL,
  headers jsonb NOT NULL,
  processed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT webhook_logs_pkey PRIMARY KEY (id)
);